# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wMain(object):
    def setupUi(self, wMain):
        wMain.setObjectName("wMain")
        wMain.resize(1870, 950)
        self.centralwidget = QtWidgets.QWidget(wMain)
        self.centralwidget.setStyleSheet("background : #333333;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.logo = QtWidgets.QFrame(self.tab_3)
        self.logo.setGeometry(QtCore.QRect(20, 20, 1031, 811))
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 1501, 801))
        self.layoutWidget.setObjectName("layoutWidget")
        self.loGrid = QtWidgets.QGridLayout(self.layoutWidget)
        self.loGrid.setContentsMargins(0, 0, 0, 0)
        self.loGrid.setVerticalSpacing(10)
        self.loGrid.setObjectName("loGrid")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(1510, 800, 331, 30))
        self.pushButton.setObjectName("pushButton")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(1510, 60, 331, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 441))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.toolBox.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.toolBox.setFont(font)
        self.toolBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet("")
        self.toolBox.setObjectName("toolBox")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 321, 369))
        self.page_2.setMaximumSize(QtCore.QSize(321, 16777215))
        self.page_2.setObjectName("page_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_7.addWidget(self.lineEdit_2)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_4)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.comboBox_5 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_5)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.comboBox_6 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_6)
        self.loGrid_3 = QtWidgets.QGridLayout()
        self.loGrid_3.setVerticalSpacing(10)
        self.loGrid_3.setObjectName("loGrid_3")
        self.verticalLayout_7.addLayout(self.loGrid_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_6)
        self.toolBox.addItem(self.page_2, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName("page")
        self.layoutWidget1 = QtWidgets.QWidget(self.page)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 311, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_9.addWidget(self.lineEdit_3)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_7)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_8)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_9)
        self.loGrid_4 = QtWidgets.QGridLayout()
        self.loGrid_4.setVerticalSpacing(10)
        self.loGrid_4.setObjectName("loGrid_4")
        self.verticalLayout_9.addLayout(self.loGrid_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_9.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(10, 0, 301, 22))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setObjectName("label_15")
        self.toolBox.addItem(self.page, "")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(1510, 30, 301, 22))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("color = rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 546, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_3)
        self.comboBox_10 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_10)
        self.comboBox_11 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_11)
        self.pushButton_buscar1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_buscar1.setObjectName("pushButton_buscar1")
        self.horizontalLayout_6.addWidget(self.pushButton_buscar1)
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 60, 541, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 541, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 280, 541, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setStyleSheet("color = rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.pushButton_buscar2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_buscar2.setObjectName("pushButton_buscar2")
        self.horizontalLayout_7.addWidget(self.pushButton_buscar2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_4)
        self.calendarWidget.setGeometry(QtCore.QRect(1480, 60, 351, 281))
        self.calendarWidget.setObjectName("calendarWidget")
        self.progressBar = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar.setGeometry(QtCore.QRect(20, 350, 541, 24))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 40, 1811, 521))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.loGrid_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.loGrid_2.setContentsMargins(0, 0, 0, 0)
        self.loGrid_2.setVerticalSpacing(10)
        self.loGrid_2.setObjectName("loGrid_2")
        self.columnView = QtWidgets.QColumnView(self.layoutWidget_2)
        self.columnView.setObjectName("columnView")
        self.loGrid_2.addWidget(self.columnView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 861, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listView = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout_8.addWidget(self.listView)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.img_contenedor_ayuda = QtWidgets.QFrame(self.tab_2)
        self.img_contenedor_ayuda.setGeometry(QtCore.QRect(880, 20, 191, 161))
        self.img_contenedor_ayuda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_contenedor_ayuda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_contenedor_ayuda.setObjectName("img_contenedor_ayuda")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        wMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1870, 28))
        self.menubar.setStyleSheet("background : grey;\n"
"color : white;\n"
"border-bottom-style: outset;\n"
"border-bottom-width: 1px;\n"
"border-bottom-color: #222222;")
        self.menubar.setObjectName("menubar")
        wMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wMain)
        self.statusbar.setStyleSheet("background : grey;\n"
"color : white;\n"
"border-top-style: outset;\n"
"border-top-width: 1px;\n"
"border-top-color: #222222;")
        self.statusbar.setObjectName("statusbar")
        wMain.setStatusBar(self.statusbar)

        self.retranslateUi(wMain)
        self.tabWidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(0)
        self.pushButton.clicked.connect(wMain.close)
        self.pushButton_buscar2.clicked.connect(self.tabWidget.show)
        QtCore.QMetaObject.connectSlotsByName(wMain)

    def retranslateUi(self, wMain):
        _translate = QtCore.QCoreApplication.translate
        wMain.setWindowTitle(_translate("wMain", "Visor Xtam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("wMain", "INICIO"))
        self.pushButton.setText(_translate("wMain", "SALIR"))
        self.label_6.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">MODULO DE STREAMING</span></p></body></html>"))
        self.label_7.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">URL</span></p></body></html>"))
        self.label_8.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">RESOLUCIÓN</span></p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("wMain", "640X480"))
        self.comboBox_4.setItemText(1, _translate("wMain", "800X600"))
        self.comboBox_4.setItemText(2, _translate("wMain", "1280X720"))
        self.comboBox_4.setItemText(3, _translate("wMain", "1920X1080"))
        self.label_9.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">FPS</span></p></body></html>"))
        self.comboBox_5.setItemText(0, _translate("wMain", "5"))
        self.comboBox_5.setItemText(1, _translate("wMain", "10"))
        self.comboBox_5.setItemText(2, _translate("wMain", "15"))
        self.comboBox_5.setItemText(3, _translate("wMain", "20"))
        self.comboBox_5.setItemText(4, _translate("wMain", "25"))
        self.comboBox_5.setItemText(5, _translate("wMain", "30"))
        self.label_10.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">BITRATE</span></p></body></html>"))
        self.comboBox_6.setItemText(0, _translate("wMain", "691  kbps"))
        self.comboBox_6.setItemText(1, _translate("wMain", "1440 kbps"))
        self.comboBox_6.setItemText(2, _translate("wMain", "2211  kbps"))
        self.comboBox_6.setItemText(3, _translate("wMain", "55987 kbps"))
        self.pushButton_3.setText(_translate("wMain", "INICIAR"))
        self.label_11.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">URL</span></p></body></html>"))
        self.label_12.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">RESOLUCIÓN</span></p></body></html>"))
        self.comboBox_7.setItemText(0, _translate("wMain", "640X480"))
        self.comboBox_7.setItemText(1, _translate("wMain", "800X600"))
        self.comboBox_7.setItemText(2, _translate("wMain", "1280X720"))
        self.comboBox_7.setItemText(3, _translate("wMain", "1920X1080"))
        self.label_13.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">FPS</span></p></body></html>"))
        self.comboBox_8.setItemText(0, _translate("wMain", "5"))
        self.comboBox_8.setItemText(1, _translate("wMain", "10"))
        self.comboBox_8.setItemText(2, _translate("wMain", "15"))
        self.comboBox_8.setItemText(3, _translate("wMain", "20"))
        self.comboBox_8.setItemText(4, _translate("wMain", "25"))
        self.comboBox_8.setItemText(5, _translate("wMain", "30"))
        self.label_14.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">BITRATE</span></p></body></html>"))
        self.comboBox_9.setItemText(0, _translate("wMain", "691  kbps"))
        self.comboBox_9.setItemText(1, _translate("wMain", "1440 kbps"))
        self.comboBox_9.setItemText(2, _translate("wMain", "2211  kbps"))
        self.comboBox_9.setItemText(3, _translate("wMain", "55987 kbps"))
        self.pushButton_4.setText(_translate("wMain", "INICIAR"))
        self.label_15.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">MODULO DE GRABACIÓN</span></p></body></html>"))
        self.label_16.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">MODULOS XTAM</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("wMain", "MONITOR"))
        self.comboBox.setItemText(0, _translate("wMain", "AÑO"))
        self.comboBox.setItemText(1, _translate("wMain", "2020"))
        self.comboBox.setItemText(2, _translate("wMain", "2021"))
        self.comboBox.setItemText(3, _translate("wMain", "2022"))
        self.comboBox.setItemText(4, _translate("wMain", "2023"))
        self.comboBox.setItemText(5, _translate("wMain", "2024"))
        self.comboBox.setItemText(6, _translate("wMain", "2025"))
        self.comboBox_2.setItemText(0, _translate("wMain", "MES"))
        self.comboBox_2.setItemText(1, _translate("wMain", "01"))
        self.comboBox_2.setItemText(2, _translate("wMain", "02"))
        self.comboBox_2.setItemText(3, _translate("wMain", "03"))
        self.comboBox_2.setItemText(4, _translate("wMain", "04"))
        self.comboBox_2.setItemText(5, _translate("wMain", "05"))
        self.comboBox_2.setItemText(6, _translate("wMain", "06"))
        self.comboBox_2.setItemText(7, _translate("wMain", "07"))
        self.comboBox_2.setItemText(8, _translate("wMain", "08"))
        self.comboBox_2.setItemText(9, _translate("wMain", "09"))
        self.comboBox_2.setItemText(10, _translate("wMain", "10"))
        self.comboBox_2.setItemText(11, _translate("wMain", "11"))
        self.comboBox_2.setItemText(12, _translate("wMain", "12"))
        self.comboBox_3.setItemText(0, _translate("wMain", "DIA"))
        self.comboBox_3.setItemText(1, _translate("wMain", "1"))
        self.comboBox_3.setItemText(2, _translate("wMain", "2"))
        self.comboBox_3.setItemText(3, _translate("wMain", "3"))
        self.comboBox_3.setItemText(4, _translate("wMain", "4"))
        self.comboBox_3.setItemText(5, _translate("wMain", "5"))
        self.comboBox_3.setItemText(6, _translate("wMain", "6"))
        self.comboBox_3.setItemText(7, _translate("wMain", "7"))
        self.comboBox_3.setItemText(8, _translate("wMain", "8"))
        self.comboBox_3.setItemText(9, _translate("wMain", "9"))
        self.comboBox_3.setItemText(10, _translate("wMain", "10"))
        self.comboBox_3.setItemText(11, _translate("wMain", "11"))
        self.comboBox_3.setItemText(12, _translate("wMain", "12"))
        self.comboBox_3.setItemText(13, _translate("wMain", "13"))
        self.comboBox_3.setItemText(14, _translate("wMain", "14"))
        self.comboBox_3.setItemText(15, _translate("wMain", "15"))
        self.comboBox_3.setItemText(16, _translate("wMain", "16"))
        self.comboBox_3.setItemText(17, _translate("wMain", "17"))
        self.comboBox_3.setItemText(18, _translate("wMain", "18"))
        self.comboBox_3.setItemText(19, _translate("wMain", "19"))
        self.comboBox_3.setItemText(20, _translate("wMain", "20"))
        self.comboBox_3.setItemText(21, _translate("wMain", "21"))
        self.comboBox_3.setItemText(22, _translate("wMain", "22"))
        self.comboBox_3.setItemText(23, _translate("wMain", "23"))
        self.comboBox_3.setItemText(24, _translate("wMain", "24"))
        self.comboBox_3.setItemText(25, _translate("wMain", "25"))
        self.comboBox_3.setItemText(26, _translate("wMain", "26"))
        self.comboBox_3.setItemText(27, _translate("wMain", "27"))
        self.comboBox_3.setItemText(28, _translate("wMain", "28"))
        self.comboBox_3.setItemText(29, _translate("wMain", "29"))
        self.comboBox_3.setItemText(30, _translate("wMain", "30"))
        self.comboBox_3.setItemText(31, _translate("wMain", "31"))
        self.comboBox_10.setItemText(0, _translate("wMain", "HORA"))
        self.comboBox_10.setItemText(1, _translate("wMain", "1"))
        self.comboBox_10.setItemText(2, _translate("wMain", "2"))
        self.comboBox_10.setItemText(3, _translate("wMain", "3"))
        self.comboBox_10.setItemText(4, _translate("wMain", "4"))
        self.comboBox_10.setItemText(5, _translate("wMain", "5"))
        self.comboBox_10.setItemText(6, _translate("wMain", "6"))
        self.comboBox_10.setItemText(7, _translate("wMain", "7"))
        self.comboBox_10.setItemText(8, _translate("wMain", "8"))
        self.comboBox_10.setItemText(9, _translate("wMain", "9"))
        self.comboBox_10.setItemText(10, _translate("wMain", "10"))
        self.comboBox_10.setItemText(11, _translate("wMain", "11"))
        self.comboBox_10.setItemText(12, _translate("wMain", "12"))
        self.comboBox_10.setItemText(13, _translate("wMain", "13"))
        self.comboBox_10.setItemText(14, _translate("wMain", "14"))
        self.comboBox_10.setItemText(15, _translate("wMain", "15"))
        self.comboBox_10.setItemText(16, _translate("wMain", "16"))
        self.comboBox_10.setItemText(17, _translate("wMain", "17"))
        self.comboBox_10.setItemText(18, _translate("wMain", "18"))
        self.comboBox_10.setItemText(19, _translate("wMain", "19"))
        self.comboBox_10.setItemText(20, _translate("wMain", "20"))
        self.comboBox_10.setItemText(21, _translate("wMain", "21"))
        self.comboBox_10.setItemText(22, _translate("wMain", "22"))
        self.comboBox_10.setItemText(23, _translate("wMain", "23"))
        self.comboBox_10.setItemText(24, _translate("wMain", "24"))
        self.comboBox_11.setItemText(0, _translate("wMain", "MINUTO"))
        self.comboBox_11.setItemText(1, _translate("wMain", "00"))
        self.comboBox_11.setItemText(2, _translate("wMain", "01"))
        self.comboBox_11.setItemText(3, _translate("wMain", "02"))
        self.comboBox_11.setItemText(4, _translate("wMain", "03"))
        self.comboBox_11.setItemText(5, _translate("wMain", "04"))
        self.comboBox_11.setItemText(6, _translate("wMain", "05"))
        self.comboBox_11.setItemText(7, _translate("wMain", "06"))
        self.comboBox_11.setItemText(8, _translate("wMain", "07"))
        self.comboBox_11.setItemText(9, _translate("wMain", "08"))
        self.comboBox_11.setItemText(10, _translate("wMain", "09"))
        self.comboBox_11.setItemText(11, _translate("wMain", "10"))
        self.comboBox_11.setItemText(12, _translate("wMain", "11"))
        self.comboBox_11.setItemText(13, _translate("wMain", "12"))
        self.comboBox_11.setItemText(14, _translate("wMain", "13"))
        self.comboBox_11.setItemText(15, _translate("wMain", "14"))
        self.comboBox_11.setItemText(16, _translate("wMain", "15"))
        self.comboBox_11.setItemText(17, _translate("wMain", "16"))
        self.comboBox_11.setItemText(18, _translate("wMain", "17"))
        self.comboBox_11.setItemText(19, _translate("wMain", "18"))
        self.comboBox_11.setItemText(20, _translate("wMain", "19"))
        self.comboBox_11.setItemText(21, _translate("wMain", "20"))
        self.comboBox_11.setItemText(22, _translate("wMain", "21"))
        self.comboBox_11.setItemText(23, _translate("wMain", "22"))
        self.comboBox_11.setItemText(24, _translate("wMain", "23"))
        self.comboBox_11.setItemText(25, _translate("wMain", "24"))
        self.comboBox_11.setItemText(26, _translate("wMain", "25"))
        self.comboBox_11.setItemText(27, _translate("wMain", "26"))
        self.comboBox_11.setItemText(28, _translate("wMain", "27"))
        self.comboBox_11.setItemText(29, _translate("wMain", "28"))
        self.comboBox_11.setItemText(30, _translate("wMain", "29"))
        self.comboBox_11.setItemText(31, _translate("wMain", "30"))
        self.comboBox_11.setItemText(32, _translate("wMain", "31"))
        self.comboBox_11.setItemText(33, _translate("wMain", "32"))
        self.comboBox_11.setItemText(34, _translate("wMain", "33"))
        self.comboBox_11.setItemText(35, _translate("wMain", "34"))
        self.comboBox_11.setItemText(36, _translate("wMain", "35"))
        self.comboBox_11.setItemText(37, _translate("wMain", "36"))
        self.comboBox_11.setItemText(38, _translate("wMain", "37"))
        self.comboBox_11.setItemText(39, _translate("wMain", "38"))
        self.comboBox_11.setItemText(40, _translate("wMain", "39"))
        self.comboBox_11.setItemText(41, _translate("wMain", "40"))
        self.comboBox_11.setItemText(42, _translate("wMain", "41"))
        self.comboBox_11.setItemText(43, _translate("wMain", "42"))
        self.comboBox_11.setItemText(44, _translate("wMain", "43"))
        self.comboBox_11.setItemText(45, _translate("wMain", "44"))
        self.comboBox_11.setItemText(46, _translate("wMain", "45"))
        self.comboBox_11.setItemText(47, _translate("wMain", "46"))
        self.comboBox_11.setItemText(48, _translate("wMain", "47"))
        self.comboBox_11.setItemText(49, _translate("wMain", "48"))
        self.comboBox_11.setItemText(50, _translate("wMain", "49"))
        self.comboBox_11.setItemText(51, _translate("wMain", "50"))
        self.comboBox_11.setItemText(52, _translate("wMain", "51"))
        self.comboBox_11.setItemText(53, _translate("wMain", "52"))
        self.comboBox_11.setItemText(54, _translate("wMain", "53"))
        self.comboBox_11.setItemText(55, _translate("wMain", "54"))
        self.comboBox_11.setItemText(56, _translate("wMain", "55"))
        self.comboBox_11.setItemText(57, _translate("wMain", "56"))
        self.comboBox_11.setItemText(58, _translate("wMain", "57"))
        self.comboBox_11.setItemText(59, _translate("wMain", "58"))
        self.comboBox_11.setItemText(60, _translate("wMain", "59"))
        self.pushButton_buscar1.setText(_translate("wMain", "BUSCAR"))
        self.label.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">BUSQUEDA POR CALENDARIO</span></p></body></html>"))
        self.label_2.setText(_translate("wMain", "<html><head/><body><p><span style=\" color:#ffffff;\">BUSCADOR</span></p></body></html>"))
        self.pushButton_buscar2.setText(_translate("wMain", "BUSCAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("wMain", "BUSCAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("wMain", "FTP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("wMain", "AYUDA"))

